# Generated by Django 2.2 on 2019-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190430_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_futsal_admin',
            field=models.BooleanField(default=False),
        ),
    ]
