# Generated by Django 2.2 on 2019-05-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('users', '0004_auto_20190430_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='futsal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.FutsalCompany'),
        ),
    ]
