# Generated by Django 2.2 on 2019-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190502_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('PLAYING', 'PLAYING'), ('COMPLETE', 'COMPLETE'), ('CANCELED', 'CANCELED')], default='CONFIRMED', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=50),
        ),
    ]
