# Generated by Django 2.2 on 2019-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190503_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalcompany',
            name='futsal_name',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
