# Generated by Django 2.2 on 2019-05-02 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pages.models
import pages.myFields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalCompany',
            fields=[
                ('futsal_id', models.AutoField(primary_key=True, serialize=False)),
                ('futsal_name', models.CharField(max_length=155)),
                ('opening_time', models.TimeField(default=pages.models.getDefaultOpeningTime)),
                ('closing_time', models.TimeField(default=pages.models.getDefaultClosingTime)),
            ],
            options={
                'verbose_name_plural': 'futsal companies',
                'ordering': ['futsal_name'],
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('ground_id', models.AutoField(primary_key=True, serialize=False)),
                ('ground_number', models.IntegerField(unique=True)),
                ('ground_name', models.CharField(max_length=155, unique=True)),
                ('futsalCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.FutsalCompany')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=155)),
                ('player_address', models.CharField(blank=True, max_length=220, null=True)),
                ('player_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroundPrice',
            fields=[
                ('price_segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', pages.myFields.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Ground')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('PLAYING', 'PLAYING'), ('COMPLETE', 'COMPLETE'), ('CANCELED', 'CANCELED')], max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=50)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Ground')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Player')),
            ],
        ),
    ]
